services:
  kirby:
    container_name: storiedibit
    build: .
    ports:
      - "8084:80"
      - "8085:443"
    logging:
      driver: local
    volumes:
      - .:/app
      - ../ssh:/home/application/.ssh
