blueprint: page

title: Newsletter

columns:
  main:
    width: 2/3
    fields:
      text:
        type: blocks
        fieldsets:
          - text
          - heading
          - image
          - quote
          - code
          - markdown
          - gallery
          - line
          - video
          - list
          - newsletter-section
          - newsletter-subsection

  sidebar:
    width: 1/3
    sections:
      info:
        type: info
        headline: Number
        icon: list-numbers
        text: "{{ page.num }}"
      files:
        type: files
        info: "{{ file.dimensions }} - {{ file.nicesize }}"
        image:
          back: white
          cover: true
