blueprint: page

title: Newsletter
#num: '{{ page.date.toDate("Ymd") }}'

columns:
  main:
    width: 2/3
    fields:
      text:
        type: blocks
        fieldsets:
          - text
          - heading
          - image
          - quote
          - code
          - markdown
          - gallery
          - line
          - video
          - list
          - newsletter-section
          - newsletter-subsection

  sidebar:
    width: 1/3
    sections:
      files:
        type: files
        info: "{{ file.dimensions }} - {{ file.nicesize }}"
