blueprint: page

title: Newsletter
icon: text-left

columns:
  left:
    width: 1/2
    sections:
      drafts:
        type: pages
        template: newsletter
        parent: kirby.page("newsletter")
        label: Drafts
        status: draft

      unlisted:
        type: pages
        template: newsletter
        parent: kirby.page("newsletter")
        label: Unlisted
        status: unlisted

  right:
    width: 1/2
    sections:
      published:
        type: pages
        template: newsletter
        parent: kirby.page("newsletter")
        label: Published
        status: listed
        info: "#{{ page.num }}"
        sortBy: num desc
