blueprint: page

title: Newsletter

columns:
  main:
    width: 2/3
    fields:
      text:
        type: blocks
        fieldsets:
          - text
          - image
          - newsletter-v2-section-header
          - newsletter-v2-section-title
          - newsletter-sources
          - newsletter-subscribe
          - newsletter-thenumber
          - newsletter-only-email
          - newsletter-only-archive
          - list
          - quote
          - line
          - newsletter-section
          - newsletter-subsection
          - heading
          - code
          - markdown
          - gallery
          - video

  sidebar:
    width: 1/3
    sections:
      info:
        type: info
        headline: Number
        icon: list-numbers
        text: "{{ page.num }}"
      files:
        type: files
        info: "{{ file.dimensions }} - {{ file.nicesize }}"
        image:
          back: white
          cover: true
